name: Build

on:
  pull_request:
    paths:
        - '.github/workflows/baseline-profiles.yaml'
        - 'baseline-profiles/**'
    branches:
      - main
      - end
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Build project 
        working-directory: baseline-profiles
        run: ./gradlew :app:assembleDebug